### ISSUE TITLE
Traduction des schmas JSON en scripts SQL

### ISSUE THREAD

**Issue by GT-CNIG-DDU** [cnigfr/schema-sites-economiques#34]
Bonjour @Pierlou,

Lors du dernier SG ZAE, @Mavialle a posé la question de savoir si les schemas JSON peuvent être traduits en script SQL afin de créer la structure d'une base de données.
Peux-tu nous répondre sur la faisabilité.
D'ailleurs peut-être un outil existe-t-il déjà ?

à bientôt,
@GT-CNIG-DDU 

_PS : Je pourrai dupliquer cette issue sur le [Github schema.data.gouv](https://github.com/etalab/schema.data.gouv.fr/issues) si tu le juges utile._

**Comment by Pierlou** [comment]
Bonjour Arnauld (?),

Cela ne devrait techniquement pas poser problème, il suffira de convertir les champs du schéma en colonnes avec le type associé. En faisant un petit tour d'horizon, je suis tombé sur [cette librairie python](https://github.com/frictionlessdata/tableschema-sql-py) qui semble faire exactement cela.

**Comment by GT-CNIG-DDU** [comment]
Vu et effectivement cela semble correspondre exactement au besoin !
@Mavialle suit nos échanges.
Merci Pierlou !

**Comment by Doctor-Who** [comment]
Merci pour cette ressource, pourrait on avoir une exemple de commande pour générer le standard dans une base PostGreSQL à partir du schema.json ?

**Comment by Pierlou** [comment]
Bonjour, une solution possible serait :
```
import json
from tableschema_sql.mapper import Mapper

with open('schema.json', 'r', encoding='utf8') as f:
    schema = json.load(f)
    f.close()

mapper = Mapper(prefix='')
query = "CREATE TABLE my_table (\n"
for col in mapper.convert_descriptor(bucket='', descriptor=schema)[0]:
    query += f'{col} {col.type},\n'
query += ')'
print(query)
```
Par exemple avec [ce schéma](https://github.com/cnigfr/schema-sites-economiques/schema/pole-eco)

**Comment by Doctor-Who** [comment]
Merci je vais tester.
